<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJO0MPU5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJO0MPU5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJO0MPU5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJO0MPU5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJO0MPU5\App_KernelDevDebugContainer([
    'container.build_hash' => 'JO0MPU5',
    'container.build_id' => '041ecd7a',
    'container.build_time' => 1766751960,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJO0MPU5');
