db.url=jdbc:postgresql://ep-broad-dust-aghwyfoo-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require
db.user=neondb_owner
db.password=npg_JUX9SQMB6Cpw

cloudinary.cloud_name=derru3bz9
cloudinary.api_key=162132438588965
cloudinary.api_secret=nIor2bZj0Su0Tvfhqz3eFFALVwY
